bug: Parsing error: Cannot find module 'next/babel' Require stack: - C:\Users\Administrator\Desktop\Together-Piano\Together-Piano\frontend\node_modules\next\dist\compiled\babel\bundle.js - C:\Users\Administrator\Desktop\Together-Piano\Together-Piano\frontend\node_modules\next\dist\compiled\babel\eslint-parser.js - C:\Users\Administrator\Desktop\Together-Piano\Together-Piano\frontend\node_modules\eslint-config-next\parser.js - C:\Users\Administrator\Desktop\Together-Piano\Together-Piano\frontend\node_modules\@eslint\eslintrc\dist\eslintrc.cjs
Make sure that all the Babel plugins and presets you are using
are defined as dependencies or devDependencies in your package.json
file. It's possible that the missing plugin is loaded by a preset
you are using that forgot to add the plugin to its dependencies: you
can workaround this problem by explicitly adding the missing package
to your top-level package.json.eslint